# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

circular_asd_wrapper <- function(X, ray) {
    .Call(`_simplicialdepth_circular_asd_wrapper`, X, ray)
}

circular_asd_all_arcs_wrapper <- function(points_mat) {
    .Call(`_simplicialdepth_circular_asd_all_arcs_wrapper`, points_mat)
}

SDk_wrapper <- function(Xinput_mat, x_vec, k) {
    .Call(`_simplicialdepth_SDk_wrapper`, Xinput_mat, x_vec, k)
}

SDk_parallel_wrapper <- function(Xinput_mat, q, k) {
    .Call(`_simplicialdepth_SDk_parallel_wrapper`, Xinput_mat, q, k)
}

simplicial_depth_2d_wrapper <- function(points_mat, q_vec) {
    .Call(`_simplicialdepth_simplicial_depth_2d_wrapper`, points_mat, q_vec)
}

spherical_asd_wrapper <- function(P_mat, ray_vec) {
    .Call(`_simplicialdepth_spherical_asd_wrapper`, P_mat, ray_vec)
}

