# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

circular_asd <- function(X, ray) {
    .Call(`_simplicialdepth_circular_asd`, X, ray)
}

circular_asd_all_arcs <- function(points_mat) {
    .Call(`_simplicialdepth_circular_asd_all_arcs`, points_mat)
}

SDk <- function(Xinput_mat, x_vec, k) {
    .Call(`_simplicialdepth_SDk`, Xinput_mat, x_vec, k)
}

SDk_parallel <- function(Xinput_mat, q, k) {
    .Call(`_simplicialdepth_SDk_parallel`, Xinput_mat, q, k)
}

simplicial_depth_2d <- function(points_mat, q_vec) {
    .Call(`_simplicialdepth_simplicial_depth_2d`, points_mat, q_vec)
}

spherical_asd <- function(P_mat, ray_vec) {
    .Call(`_simplicialdepth_spherical_asd`, P_mat, ray_vec)
}

