# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

circular_asd_wrapper <- function(X, q) {
    .Call(`_simplicialdepth_circular_asd_wrapper`, X, q)
}

circular_asd_all_points_wrapper <- function(points_mat) {
    .Call(`_simplicialdepth_circular_asd_all_points_wrapper`, points_mat)
}

SDk_wrapper <- function(Xinput_mat, x_vec, k) {
    .Call(`_simplicialdepth_SDk_wrapper`, Xinput_mat, x_vec, k)
}

SDk_parallel_wrapper <- function(Xinput_mat, x_vec, k) {
    .Call(`_simplicialdepth_SDk_parallel_wrapper`, Xinput_mat, x_vec, k)
}

simplicial_depth_2d_wrapper <- function(q_vec, points_mat) {
    .Call(`_simplicialdepth_simplicial_depth_2d_wrapper`, q_vec, points_mat)
}

spherical_asd_wrapper <- function(ray_vec, P_mat) {
    .Call(`_simplicialdepth_spherical_asd_wrapper`, ray_vec, P_mat)
}

